Portfolio/urls.py
from django.urls import path
from . import views

app_name = 'Portfolio'

urlpatterns = [
    path('upload/', views.portfolio_create, name='create')
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns=[
    path('', views.main, name = 'main'),
    path('post_create/', views.post_create, name = 'post_create'),
    path('<int:pk>/comment/', views.comment_create, name = 'comment_create'),
    path('<int:pk>/edit/',views.post_edit, name = 'post_edit'),
    path('<int:pk>/delete/',views.post_delete, name = 'post_delete'),
    path('<int:pk>/', views.post_read, name = 'post_read'),
    path('post_list/',views.post_list, name = 'post_list'),

    path('login/',auth_views.LoginView.as_view(), name='login'), 
    path('signup/', views.CreateUserView.as_view(), name = 'signup'),  
    path('signup/done', views.RegisteredView.as_view(), name = 'create_user_done'),
    path('login_done/', views.RegisteredView.as_view(), name = 'login_done'),
    path('logout/',auth_views.LogoutView.as_view(), name="logout"),  
    path('permission_denied/', views.permission_denied, name = 'permission_denied'),  


]

studyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import Portfolio.views
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.main, name='main'),
    path('Portfolio/',Portfolio.views.portfolio, name='Portfolio'),
    path('blog/', include('blog.urls')),
    path('Portfolio/', include('Portfolio.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portfolio/models.py
from django.db import models
# from django.urlresolvers import reverse_lazy
# Create your models here.
class Portfolio(models.Model):
    title = models.CharField(max_length=255,default='SOME STRING')
    image = models.ImageField(
        upload_to="C:/Users/user/Desktop/master/studyProject-1/media"
    )
    content = models.TextField(default="Some String")
    # created_at = models.DateTimeField(auto_now_add=True, default="some") 
      
    # def get_absolute_url(self):
    #     url = reverse_lazy('Portfolio', kwargs={'pk': self.pk})
    #     return url
        
    def __str__(self):
        return self.title

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Post(models.Model):

    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return self.title
    

class Comment(models.Model):

    post = models.ForeignKey('blog.Post',on_delete=models.CASCADE )
    text = models.TextField()
  


class User(AbstractUser):
    class Meta:
        permissions = [
            ['can_view_post', 'Can view post'],
        ]

Portfolio/forms.py
from .models import Portfolio
from django import forms

class PortfolioForm(forms.ModelForm):
   class Meta:
        model = Portfolio
        fields = ['image', 'title',]

blog/forms.py
from .models import Post, Comment, User
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

class CreateUserForm(UserCreationForm): 
    email = forms.EmailField(required=True) 

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True): 
        user = super(CreateUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
    
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email')

Portfolio/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Portfolio
from .forms import PortfolioForm


# Create your views here.

def portfolio(request):
    Portfolios = Portfolio.objects
    return render(request,'portfolio.html', {'portfolios':Portfolios})
    
def portfolio_create(request):    
    if request.method == 'POST':
        Portfolio_form = PortfolioForm(request.POST,request.FILES)
        if Portfolio_form.is_valid():
            Portfolio = Portfolio_form.save(commit=False)
            Portfolio.save()
            return redirect('portfolio')
        
    else:
        Portfolio_form = PortfolioForm()


    return render(request, 'upload.html', {
        'Portfolio_form':Portfolio_form,
    }) 

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Post, Comment, User

from django.http import HttpResponse
from .forms import PostForm, CommentForm, CreateUserForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.decorators import permission_required,login_required
from django.views import View

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission


def main(request):
    return render(request,'blog/main.html')

def post_list(request):
    posts = Post.objects.all()

    return render(request,'blog/post_list.html',{"posts":posts})



#create
def post_create(request):
    if request.method == 'POST':
        Post_form = PostForm(request.POST)

        if Post_form.is_valid():
            post = Post_form.save()
            return HttpResponse('생성완료')
        
    else:
        Post_form = PostForm()

    return render(request, 'blog/post_create.html', {
        'Post_form':Post_form,
    }) 



def comment_create(request, pk):
    post =  get_object_or_404(Post, id = pk)
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit = False)
        comment.post = post
        comment = form.save()
    
    return redirect(post)



#read
def post_read(request,pk):
    post = get_object_or_404(Post, id=pk)
    form = CommentForm()
    return render(request,'blog/post_read.html',{
        'post':post,
        'form':form,
        })


#update
@permission_required('can_add_log_entry')
def post_edit(request, pk):
    post = get_object_or_404(Post, id = pk)

    if request.method =='POST':
        Post_form = PostForm(request.POST, instance = post)

        if Post_form.is_valid():
            post = Post_form.save()
            return HttpResponse('수정완료')
    else:
        Post_form = PostForm(instance = post)
    
    return render(request, 'blog/post_create.html',{
        'Post_form':Post_form,
    })


#delete
def post_delete(request, pk):
    post = get_object_or_404(Post, id = pk)
    post.delete()
    return render(request, 'blog/main.html')

class CreateUserView(CreateView):
    template_name = 'registration/signup.html'
    form_class =  CreateUserForm 
    success_url = reverse_lazy('blog:create_user_done') 

class RegisteredView(TemplateView): 
    template_name = 'registration/login_done.html' 

def permission_denied(request):
    return render(request, 'registration/permission_denied.html',{
    })



def profile(request):
    if not request.user.is_authenticated:
        data = {'username': request.user, 'is_authenticated': request.user.is_authenticated}
    else:
        data = {'last_login': request.user.last_login, 'username': request.user.username,
                'password': request.user.password, 'is_authenticated': request.user.is_authenticated}
    return render(request, 'profile.html', context={'data': data}) 
    

Portfolio/templates/Portfolio/upload1.html
{% extends "portfolio.html" %}

{% load staticfiles %}

{% block main %}
<h2>{{ post.title }}</h2>
<form method='post' action="" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>
<a id="id_uploaded_file" href="{ uploadFileModel.file.url }" download>{ uploadFileModel.file.name }</a>


{% if post.photo %}
path :{{ post.photo.path }} # /Users/nickname/documents/practice/media/jeju_pic.png
url : {{ post.photo.url }} # /media/jeju_pic.png
<img src="{{ post.photo.url }}" alt="">
{% endif %}

{% endblock %}

Portfolio/templates/portfolio.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Album example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
</head>

<body>

{% extends 'base.html'%}
{% block content %}

<h1>포트폴리오 페이지입니다</h1>
    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">About</h4>
                        <p class="text-muted">Add some information about the album below, the author, or any other
                            background context. Make it a few sentences long so folks can pick up some informative
                            tidbits. Then, link them off to some social networking sites or contact information.</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contact</h4>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Follow on Twitter</a></li>
                            <li><a href="#" class="text-white">Like on Facebook</a></li>
                            <li><a href="#" class="text-white">Email me</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container d-flex justify-content-between">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                        <circle cx="12" cy="13" r="4"></circle>
                    </svg>
                    <strong>Album</strong>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>
    {% load staticfiles %}
    <main role="main">
       
        <section class="jumbotron text-center">
            <div class="container">
                <img src="{% static 'cap.jpg' %}" alt="logo">
                <h1 class="jumbotron-heading">Album example</h1>
                <p class="lead text-muted">Something short and leading about the collection below—its contents, the
                    creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it
                    entirely.</p>
                <p>
                    <a href="{% url 'portfolio_create' %}" class="btn btn-primary my-2">Create</a>
                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>
                </p>
            </div>
        </section>
<div class="album py-5 bg-light">
  <div class="container">
	  <div class="row">
      {% for portfolio in portfolios.all %}
	    <div class="col-md-4">
	      <div class="card mb-4 shadow-sm">
	        <img class="card-img-top" src="{{ portfolio.image.url }}" alt=" Card image cap">
	        <div class="card-body">
	          <h4>{{ portfolio.title }}</h4>
              <p class="card-text">{{ portfolio.content }}</p>
	        </div>
	      </div>
        </div>
        {% endfor %}
    </div>
  </div>
</div>

    </main>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#">Back to top</a>
            </p>
            <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
            <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
                    started guide</a>.</p>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
{% endblock %}
</body>

</html>

Portfolio/templates/upload.html
<form action="{% url 'create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">제출</button>
</form>

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title> Misun Local Library</title>
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul>
                    <li><a href="{% url 'blog:main'%}">Home</a></li>
                    {% if user.is_authenticated %}
                    <li>
                        <h1>로그인 되어있음</h1> <br> User : {{user.username}}
                    </li>
                    <li><a href="{% url 'blog:logout'%}?next={{request.path}}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'blog:login'%}?next={{request.path}}">Login</a></li>
                    <li><a href="{% url 'blog:signup'%}">회원가입</a></li>
                    <li><a href="{% url 'blog:logout' %}">로그아웃</a></li>
                    {% endif %}

                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}
               
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

blog/templates/blog/main.html
{% extends 'base.html'%}

{% block content %}
<h1>안녕하세요 멋쟁이사자 7기 김미선입니다.</h1>

<a href="{% url 'blog:post_create'%}">post 올리기</a>
<a href="{% url 'blog:post_list'%}">post 보기</a>
{% endblock %}

blog/templates/blog/post_create.html
<html>
    
{%block content %}

<form action="" method="post">
        {% csrf_token %}
        <table>
            {{Post_form.as_table}}
        </table>

        <input type="submit" value = "submit">
    </form>

{% endblock content %}


</html>

blog/templates/blog/post_list.html
<html>
{% extends 'base.html'%}
{% block content %}
{% if posts%}

{% for post in posts %} 
    <ul>
        <li><a href="{% url 'blog:post_read' post.pk %}">{{post.title}}</a></li>
    </ul>
{% endfor %}

{% else %}
<p>There are no posts in misun's library.</p>
{% endif %}
{% endblock %}
</html>

blog/templates/blog/post_login_done.html
{% block content %}
<h2>로그인이 완료되었습니다. </h2>
<br>
<a href="{% url 'blog:main'%}">메인화면가기</a> 
{% endblock content %}

blog/templates/blog/post_read.html
<html>
{% extends 'base.html'%}
{% block content %}
<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>created_date</th>
        <th>T</th>
    </tr>
    <tr>
        <td>{{post.title}}</td>
        <td>{{post.text}}</td>
        <td>{{post.created_date}}</td>
        <td>
            <ul>
                <li><a href="{% url 'blog:post_edit' post.id %}">수정하기</a></li>
                <li><a href="{% url 'blog:post_delete' post.id %}">삭제하기</a></li>
            </ul>
        </td>
    </tr>
</table>

<hr>
<form action="{% url 'blog:comment_create' post.id %}" method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value = "submit">
</form>
<hr>
{% for comment in post.comment_set.all %}
 <p>
     {{comment.text}}
 </p>

{% empty %}
    <p>답변이 없습니다</p>
{% endfor %}
{% endblock %}
</html>